### PR TITLE
Edit broader/narrower and derived periods

### PR DESCRIPTION
**Pull request by rybesh**
Implements editing and viewing of related periods (derived from, broader, narrower).

ID references to related periods are resolved in the reducer and stored as symbols on period objects. This is hacky and should be replaced with use of a backend method to resolve a period ID to a period.

Speaking of which: this pull request adds modules/periodo-ui/src/BackendContext.js which is used to access the current backend from deep in a component tree (so that internal links to other periods can be constructed). This is super handy, and having this plus utility methods on the backend object would be 🆒

### CODE REVIEW

**Comment by rybesh** [comment]
merge me

**Comment by ptgolden** [comment]
I'm having trouble merging this now. I'll do it in a little bit

**Comment by ptgolden** [comment]
If we use that BackendContext, I'd rather have it at a higher level (e.g. the application as a whole or per-resource)

**Comment by ptgolden** [comment]
I wanted to avoid making a massive merge commit, so I'm merging up to 76d750e (the commits having to do with broader/narrower relations) in #170. I'll move on to authority editing next.

**Comment by ptgolden** [comment]
> If we use that BackendContext, I'd rather have it at a higher level (e.g. the application as a whole or per-resource)

I did that in ade3a18668c0cf90457d0a3752a69d38ec48bced

**Comment by ptgolden** [comment]
Oops, there's more after 76d750e that relate to broader/narrower. I'll just create a second pull request with the rest. Sorry.

**Comment by ptgolden** [comment]
#171

**Comment by ptgolden** [comment]
OK, all of these are merged now. Can you double check that everything is working and close this PR when you get a chance?

**Comment by rybesh** [comment]
Seems to be working! Thanks.

**Pull request closed without merging**
